version: '2'
services:
    betsportv2-app:
        image: betsportv2
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://betsportv2-postgresql:5432/betsportV2
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    betsportv2-postgresql:
        extends:
            file: postgresql.yml
            service: betsportv2-postgresql
